// frontend/src/react/LtiPlatformsAdmin.tsx
/**
 * LtiPlatformsAdmin — React port of LtiPlatformsAdmin.vue.
 *
 * Admin-only screen to register / update / delete LMS platforms (Moodle, etc.)
 * for LTI 1.3. Calls `/api/v1/lti/platforms` via the shared `../api` module,
 * which requires the app's Bearer token to already be set on axios defaults
 * by your auth layer.
 *
 * Requires `react`, `react-dom`, and `axios` (peer deps). No router needed.
 */

import { useCallback, useEffect, useState } from 'react';

import {
  listLtiPlatforms,
  saveLtiPlatform,
  deleteLtiPlatform,
  type LtiPlatform,
} from '../api';

interface PlatformForm {
  name: string;
  url: string;
  clientId: string;
  authenticationEndpoint: string;
  accesstokenEndpoint: string;
  authConfigMethod: string;
  authConfigKey: string;
}

const EMPTY_FORM: PlatformForm = {
  name: 'Moodle',
  url: '',
  clientId: '',
  authenticationEndpoint: '',
  accesstokenEndpoint: '',
  authConfigMethod: 'JWK_SET',
  authConfigKey: '',
};

function errText(e: any, fallback: string): string {
  return e?.response?.data?.message || e?.message || fallback;
}

export function LtiPlatformsAdmin() {
  const [loading, setLoading] = useState(false);
  const [saving, setSaving] = useState(false);
  const [deletingId, setDeletingId] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [platforms, setPlatforms] = useState<LtiPlatform[]>([]);
  const [form, setForm] = useState<PlatformForm>({ ...EMPTY_FORM });

  const loadPlatforms = useCallback(async () => {
    setError(null);
    setLoading(true);
    try {
      setPlatforms(await listLtiPlatforms());
    } catch (e: any) {
      setError(errText(e, 'Failed to load platforms.'));
    } finally {
      setLoading(false);
    }
  }, []);

  function setField<K extends keyof PlatformForm>(key: K, value: PlatformForm[K]) {
    setForm((prev) => ({ ...prev, [key]: value }));
  }

  function resetForm() {
    setForm({ ...EMPTY_FORM });
  }

  function prefill(p: LtiPlatform) {
    setForm({
      name: p.name || 'Moodle',
      url: p.url || '',
      clientId: p.clientId || '',
      authenticationEndpoint: p.authenticationEndpoint || '',
      accesstokenEndpoint: p.accesstokenEndpoint || '',
      authConfigMethod: p.authConfigMethod || 'JWK_SET',
      authConfigKey: p.authConfigKey || '',
    });
    window.scrollTo({ top: 0, behavior: 'smooth' });
  }

  async function savePlatform() {
    setError(null);
    setSaving(true);
    try {
      await saveLtiPlatform(form);
      await loadPlatforms();
    } catch (e: any) {
      setError(errText(e, 'Failed to save platform.'));
    } finally {
      setSaving(false);
    }
  }

  async function remove(p: LtiPlatform) {
    setError(null);
    const id = p.platformId || '';
    setDeletingId(id || null);
    try {
      await deleteLtiPlatform({ platformId: id, url: p.url || '', clientId: p.clientId || '' });
      await loadPlatforms();
    } catch (e: any) {
      setError(errText(e, 'Failed to delete platform.'));
    } finally {
      setDeletingId(null);
    }
  }

  useEffect(() => {
    loadPlatforms();
  }, [loadPlatforms]);

  return (
    <div style={styles.wrap}>
      <div style={styles.panelHeader}>
        <div>
          <h1 style={styles.panelTitle}>
            <i className="fas fa-plug" style={styles.titleIcon} /> LTI Platforms
          </h1>
          <p style={styles.panelSubtitle}>
            Register and manage LMS platforms (Moodle) for LTI 1.3
          </p>
        </div>
        <div>
          <button
            style={{ ...styles.btn, ...styles.btnSecondary }}
            disabled={loading}
            onClick={loadPlatforms}
          >
            <i className="fas fa-sync-alt" /> Refresh
          </button>
        </div>
      </div>

      {error && (
        <div style={styles.alert}>
          <i className="fas fa-exclamation-triangle" />
          <span>{error}</span>
        </div>
      )}

      <div style={styles.card}>
        <h2 style={styles.cardTitle}>Add / Update Platform</h2>
        <div style={styles.formGrid}>
          <Field label="Name">
            <input
              style={styles.input}
              type="text"
              placeholder="Moodle HKU"
              value={form.name}
              onChange={(e) => setField('name', e.target.value)}
            />
          </Field>
          <Field label="Platform URL">
            <input
              style={styles.input}
              type="text"
              placeholder="https://moodle.example.com"
              value={form.url}
              onChange={(e) => setField('url', e.target.value)}
            />
          </Field>
          <Field label="Client ID">
            <input
              style={styles.input}
              type="text"
              placeholder="(from Moodle tool registration)"
              value={form.clientId}
              onChange={(e) => setField('clientId', e.target.value)}
            />
          </Field>
          <Field label="Authentication Endpoint">
            <input
              style={styles.input}
              type="text"
              placeholder="https://moodle.../auth.php"
              value={form.authenticationEndpoint}
              onChange={(e) => setField('authenticationEndpoint', e.target.value)}
            />
          </Field>
          <Field label="Access Token Endpoint">
            <input
              style={styles.input}
              type="text"
              placeholder="https://moodle.../token.php"
              value={form.accesstokenEndpoint}
              onChange={(e) => setField('accesstokenEndpoint', e.target.value)}
            />
          </Field>
          <Field label="Auth Config Method">
            <select
              style={styles.input}
              value={form.authConfigMethod}
              onChange={(e) => setField('authConfigMethod', e.target.value)}
            >
              <option value="JWK_SET">JWK_SET</option>
              <option value="JWK_KEY">JWK_KEY</option>
              <option value="RSA_KEY">RSA_KEY</option>
            </select>
          </Field>
          <Field label="Auth Config Key" wide>
            <input
              style={styles.input}
              type="text"
              placeholder="For JWK_SET: https://moodle.../certs.php"
              value={form.authConfigKey}
              onChange={(e) => setField('authConfigKey', e.target.value)}
            />
          </Field>
        </div>

        <div style={styles.actions}>
          <button
            style={{ ...styles.btn, ...styles.btnPrimary }}
            disabled={saving}
            onClick={savePlatform}
          >
            <i className="fas fa-save" /> {saving ? 'Saving…' : 'Save Platform'}
          </button>
          <button
            style={{ ...styles.btn, ...styles.btnSecondary }}
            disabled={saving}
            onClick={resetForm}
          >
            <i className="fas fa-undo" /> Reset
          </button>
        </div>
        <p style={styles.muted}>
          Calls <code>/api/v1/lti/platforms</code> (admin-only). LTI must be enabled on the backend
          (<code>LTI_ENABLED=true</code>).
        </p>
      </div>

      <div style={styles.card}>
        <h2 style={styles.cardTitle}>Registered Platforms</h2>

        {loading ? (
          <div style={styles.muted}>Loading…</div>
        ) : platforms.length === 0 ? (
          <div style={styles.muted}>No platforms registered yet.</div>
        ) : (
          <div style={{ overflowX: 'auto' }}>
            <table style={styles.table}>
              <thead>
                <tr>
                  <th style={styles.th}>Name</th>
                  <th style={styles.th}>URL</th>
                  <th style={styles.th}>Client ID</th>
                  <th style={styles.th}>Auth</th>
                  <th style={styles.th}>Token</th>
                  <th style={styles.th}>Keyset</th>
                  <th style={{ ...styles.th, width: 140 }}>Actions</th>
                </tr>
              </thead>
              <tbody>
                {platforms.map((p) => (
                  <tr key={p.platformId || `${p.url}-${p.clientId}`}>
                    <td style={styles.td}>{p.name || '-'}</td>
                    <td style={{ ...styles.td, ...styles.mono }}>{p.url || '-'}</td>
                    <td style={{ ...styles.td, ...styles.mono }}>{p.clientId || '-'}</td>
                    <td style={{ ...styles.td, ...styles.mono }}>
                      {p.authenticationEndpoint || '-'}
                    </td>
                    <td style={{ ...styles.td, ...styles.mono }}>{p.accesstokenEndpoint || '-'}</td>
                    <td style={{ ...styles.td, ...styles.mono }}>{p.authConfigKey || '-'}</td>
                    <td style={styles.td}>
                      <button style={styles.btnLink} onClick={() => prefill(p)}>
                        <i className="fas fa-pen" /> Edit
                      </button>
                      <button
                        style={{ ...styles.btnLink, ...styles.btnLinkDanger }}
                        disabled={deletingId === p.platformId}
                        onClick={() => remove(p)}
                      >
                        <i className="fas fa-trash" /> Delete
                      </button>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </div>
    </div>
  );
}

function Field(props: { label: string; wide?: boolean; children: React.ReactNode }) {
  return (
    <div style={props.wide ? { gridColumn: '1 / -1' } : undefined}>
      <label style={styles.fieldLabel}>{props.label}</label>
      {props.children}
    </div>
  );
}

const styles: Record<string, React.CSSProperties> = {
  wrap: { padding: 18 },
  panelHeader: {
    display: 'flex',
    gap: 16,
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    marginBottom: 14,
  },
  panelTitle: { margin: 0, fontSize: 20, color: '#0f172a' },
  titleIcon: { marginRight: 8, color: '#0ea5e9' },
  panelSubtitle: { margin: '6px 0 0', color: '#64748b' },
  card: {
    background: '#fff',
    border: '1px solid #e2e8f0',
    borderRadius: 12,
    padding: 16,
    marginBottom: 14,
  },
  cardTitle: { margin: '0 0 12px', fontSize: 16, color: '#0f172a' },
  formGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(2, minmax(0, 1fr))',
    gap: 12,
  },
  fieldLabel: {
    display: 'block',
    fontWeight: 700,
    fontSize: 12,
    marginBottom: 6,
    color: '#334155',
  },
  input: {
    width: '100%',
    padding: '10px 12px',
    border: '1px solid #cbd5e1',
    borderRadius: 10,
    fontSize: 14,
    boxSizing: 'border-box',
  },
  actions: { display: 'flex', gap: 8, marginTop: 14, flexWrap: 'wrap' },
  btn: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 6,
    padding: '10px 16px',
    borderRadius: 10,
    border: '1px solid #cbd5e1',
    background: '#fff',
    cursor: 'pointer',
    fontWeight: 600,
  },
  btnPrimary: { background: '#0ea5e9', color: '#fff', borderColor: '#0ea5e9' },
  btnSecondary: { background: '#fff', color: '#0f172a' },
  muted: { color: '#64748b', fontSize: 13 },
  alert: {
    padding: '10px 14px',
    borderRadius: 10,
    marginBottom: 12,
    display: 'flex',
    gap: 8,
    alignItems: 'flex-start',
    background: '#fff1f2',
    color: '#9f1239',
    border: '1px solid #fecdd3',
  },
  table: { width: '100%', borderCollapse: 'collapse', fontSize: 13 },
  th: {
    borderBottom: '1px solid #e2e8f0',
    padding: '8px 10px',
    textAlign: 'left',
    verticalAlign: 'top',
    background: '#f8fafc',
    fontWeight: 700,
    color: '#334155',
  },
  td: {
    borderBottom: '1px solid #e2e8f0',
    padding: '8px 10px',
    textAlign: 'left',
    verticalAlign: 'top',
  },
  mono: { fontFamily: 'ui-monospace, SFMono-Regular, Menlo, monospace', wordBreak: 'break-all' },
  btnLink: {
    border: 0,
    background: 'transparent',
    color: '#0ea5e9',
    cursor: 'pointer',
    marginRight: 6,
    fontWeight: 600,
  },
  btnLinkDanger: { color: '#9f1239' },
};

export default LtiPlatformsAdmin;

// frontend/src/views/LtiPlatformsAdmin.vue
<template>
  <div class="lti-platforms">
    <div class="panel-header">
      <div class="header-content">
        <h1 class="panel-title">
          <i class="fas fa-plug"></i>
          LTI Platforms
        </h1>
        <p class="panel-subtitle">Register and manage LMS platforms (Moodle) for LTI 1.3</p>
      </div>
      <div class="header-actions">
        <button class="btn-action secondary" :disabled="loading" @click="loadPlatforms">
          <i class="fas fa-sync-alt"></i>
          Refresh
        </button>
      </div>
    </div>

    <div v-if="error" class="alert alert-danger">
      <i class="fas fa-exclamation-triangle"></i>
      <span>{{ error }}</span>
    </div>

    <div class="card">
      <h2 class="card-title">Add / Update Platform</h2>
      <div class="form-grid">
        <div class="field">
          <label>Name</label>
          <input v-model="form.name" type="text" placeholder="Moodle HKU" />
        </div>
        <div class="field">
          <label>Platform URL</label>
          <input v-model="form.url" type="text" placeholder="https://moodle.example.com" />
        </div>
        <div class="field">
          <label>Client ID</label>
          <input
            v-model="form.clientId"
            type="text"
            placeholder="(from Moodle tool registration)"
          />
        </div>
        <div class="field">
          <label>Authentication Endpoint</label>
          <input
            v-model="form.authenticationEndpoint"
            type="text"
            placeholder="https://moodle.../auth.php"
          />
        </div>
        <div class="field">
          <label>Access Token Endpoint</label>
          <input
            v-model="form.accesstokenEndpoint"
            type="text"
            placeholder="https://moodle.../token.php"
          />
        </div>
        <div class="field">
          <label>Auth Config Method</label>
          <select v-model="form.authConfigMethod">
            <option value="JWK_SET">JWK_SET</option>
            <option value="JWK_KEY">JWK_KEY</option>
            <option value="RSA_KEY">RSA_KEY</option>
          </select>
        </div>
        <div class="field field-wide">
          <label>Auth Config Key</label>
          <input
            v-model="form.authConfigKey"
            type="text"
            placeholder="For JWK_SET: https://moodle.../certs.php"
          />
        </div>
      </div>

      <div class="actions">
        <button class="btn-action primary" :disabled="saving" @click="savePlatform">
          <i class="fas fa-save"></i>
          {{ saving ? 'Saving…' : 'Save Platform' }}
        </button>
        <button class="btn-action secondary" :disabled="saving" @click="resetForm">
          <i class="fas fa-undo"></i>
          Reset
        </button>
      </div>
      <p class="muted">
        Calls <code>/api/v1/lti/platforms</code> (admin-only). LTI must be enabled on the backend
        (<code>LTI_ENABLED=true</code>).
      </p>
    </div>

    <div class="card">
      <h2 class="card-title">Registered Platforms</h2>

      <div v-if="loading" class="muted">Loading…</div>
      <div v-else-if="platforms.length === 0" class="muted">No platforms registered yet.</div>

      <div v-else class="table-wrap">
        <table class="platforms-table">
          <thead>
            <tr>
              <th>Name</th>
              <th>URL</th>
              <th>Client ID</th>
              <th>Auth</th>
              <th>Token</th>
              <th>Keyset</th>
              <th style="width: 140px">Actions</th>
            </tr>
          </thead>
          <tbody>
            <tr v-for="p in platforms" :key="p.platformId || `${p.url}-${p.clientId}`">
              <td>{{ p.name || '-' }}</td>
              <td class="mono">{{ p.url || '-' }}</td>
              <td class="mono">{{ p.clientId || '-' }}</td>
              <td class="mono">{{ p.authenticationEndpoint || '-' }}</td>
              <td class="mono">{{ p.accesstokenEndpoint || '-' }}</td>
              <td class="mono">{{ p.authConfigKey || '-' }}</td>
              <td>
                <button class="btn-link" @click="prefill(p)">
                  <i class="fas fa-pen"></i> Edit
                </button>
                <button
                  class="btn-link danger"
                  :disabled="deletingId === p.platformId"
                  @click="remove(p)"
                >
                  <i class="fas fa-trash"></i> Delete
                </button>
              </td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { onMounted, ref } from 'vue';
import {
  listLtiPlatforms,
  saveLtiPlatform,
  deleteLtiPlatform,
  type LtiPlatform,
} from '../api';

const loading = ref(false);
const saving = ref(false);
const deletingId = ref<string | null>(null);
const error = ref<string | null>(null);
const platforms = ref<LtiPlatform[]>([]);

const form = ref({
  name: 'Moodle',
  url: '',
  clientId: '',
  authenticationEndpoint: '',
  accesstokenEndpoint: '',
  authConfigMethod: 'JWK_SET',
  authConfigKey: '',
});

async function loadPlatforms() {
  error.value = null;
  loading.value = true;
  try {
    platforms.value = await listLtiPlatforms();
  } catch (e: any) {
    error.value = e?.response?.data?.message || e?.message || 'Failed to load platforms.';
  } finally {
    loading.value = false;
  }
}

function resetForm() {
  form.value = {
    name: 'Moodle',
    url: '',
    clientId: '',
    authenticationEndpoint: '',
    accesstokenEndpoint: '',
    authConfigMethod: 'JWK_SET',
    authConfigKey: '',
  };
}

function prefill(p: LtiPlatform) {
  form.value = {
    name: p.name || 'Moodle',
    url: p.url || '',
    clientId: p.clientId || '',
    authenticationEndpoint: p.authenticationEndpoint || '',
    accesstokenEndpoint: p.accesstokenEndpoint || '',
    authConfigMethod: p.authConfigMethod || 'JWK_SET',
    authConfigKey: p.authConfigKey || '',
  };
  window.scrollTo({ top: 0, behavior: 'smooth' });
}

async function savePlatform() {
  error.value = null;
  saving.value = true;
  try {
    await saveLtiPlatform(form.value);
    await loadPlatforms();
  } catch (e: any) {
    error.value = e?.response?.data?.message || e?.message || 'Failed to save platform.';
  } finally {
    saving.value = false;
  }
}

async function remove(p: LtiPlatform) {
  error.value = null;
  const id = p.platformId || '';
  deletingId.value = id || null;
  try {
    await deleteLtiPlatform({ platformId: id, url: p.url || '', clientId: p.clientId || '' });
    await loadPlatforms();
  } catch (e: any) {
    error.value = e?.response?.data?.message || e?.message || 'Failed to delete platform.';
  } finally {
    deletingId.value = null;
  }
}

onMounted(() => {
  loadPlatforms();
});
</script>

<style scoped>
.lti-platforms { padding: 18px; }
.panel-header {
  display: flex;
  gap: 16px;
  align-items: flex-start;
  justify-content: space-between;
  margin-bottom: 14px;
}
.panel-title { margin: 0; font-size: 20px; color: #0f172a; }
.panel-title i { margin-right: 8px; color: #0ea5e9; }
.panel-subtitle { margin: 6px 0 0; color: #64748b; }

.card {
  background: #fff;
  border: 1px solid #e2e8f0;
  border-radius: 12px;
  padding: 16px;
  margin-bottom: 14px;
}
.card-title { margin: 0 0 12px; font-size: 16px; color: #0f172a; }

.form-grid {
  display: grid;
  grid-template-columns: repeat(2, minmax(0, 1fr));
  gap: 12px;
}
.field-wide { grid-column: 1 / -1; }
.field label {
  display: block;
  font-weight: 700;
  font-size: 12px;
  margin-bottom: 6px;
  color: #334155;
}
.field input,
.field select {
  width: 100%;
  padding: 10px 12px;
  border: 1px solid #cbd5e1;
  border-radius: 10px;
  font-size: 14px;
}

.actions { display: flex; gap: 8px; margin-top: 14px; flex-wrap: wrap; }
.btn-action {
  display: inline-flex;
  align-items: center;
  gap: 6px;
  padding: 10px 16px;
  border-radius: 10px;
  border: 1px solid #cbd5e1;
  background: #fff;
  cursor: pointer;
  font-weight: 600;
}
.btn-action.primary { background: #0ea5e9; color: #fff; border-color: #0ea5e9; }
.btn-action.secondary { background: #fff; color: #0f172a; }
.btn-action[disabled] { opacity: 0.6; cursor: not-allowed; }

.muted { color: #64748b; font-size: 13px; }

.alert {
  padding: 10px 14px;
  border-radius: 10px;
  margin-bottom: 12px;
  display: flex;
  gap: 8px;
  align-items: flex-start;
}
.alert-danger { background: #fff1f2; color: #9f1239; border: 1px solid #fecdd3; }

.table-wrap { overflow-x: auto; }
.platforms-table {
  width: 100%;
  border-collapse: collapse;
  font-size: 13px;
}
.platforms-table th,
.platforms-table td {
  border-bottom: 1px solid #e2e8f0;
  padding: 8px 10px;
  text-align: left;
  vertical-align: top;
}
.platforms-table th { background: #f8fafc; font-weight: 700; color: #334155; }
.mono { font-family: ui-monospace, SFMono-Regular, Menlo, monospace; word-break: break-all; }

.btn-link {
  border: 0;
  background: transparent;
  color: #0ea5e9;
  cursor: pointer;
  margin-right: 6px;
  font-weight: 600;
}
.btn-link.danger { color: #9f1239; }
.btn-link:disabled { opacity: 0.5; cursor: not-allowed; }
</style>
